sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true
install: 
  - yarn install
script:
  - yarn build
  #- find ./build -type f -name '*.map' -size +1M -exec rm {} \;
  # - now --public --static --name airbnb-static-master ./build
  # - now alias
