language: node_js
node_js:
- '8'
cache:
  yarn: true
before_install:
- npm install -g now
install:
- yarn install
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy-master.sh
  on:
    branch:
    - master
    - travis