language: node_js
node_js:
- '8'
cache:
  yarn: true
before_install:
- npm install -g now
install:
- yarn install
script:
- yarn build
- ".travis/deploy-master.sh"
env:
  global:
  - secure: h7CVaF8BUUzjUNS7AfZBu2LCGSqb/2H/flsP0qlktQsu+0CuleIbAydbSUFMOPO/TqO8y8rQXn8Q9aiY0mItEcp06s/4ZvO7SQwmto+ATfGScMVutKw3E3CE1pC8dMNd+T1kDUZ2ii8hmrWtd0gLydXV4AaBHkyACpoy+5X4KJs9YBBbYruKMW04qgtL7yiK5gXxY0dVfk8qYiEMmqwa+/hEbF7D3nfdi26xu1RbGtyv6uq99nJ64N35oDLUoishFHhRp5rKfpP9s0Yw7DnV0aD7xMD15mTjJi3hltMsZ7FFrBcP2iCkIqUTMJoKdFmU5hk9PN0OTn+kxR6xPHjliK4MTmAKG4WhydYSJqdoE8aQn03kASGLua9XqzYZXvQ4r5qEBIC+n0C/vRS/f01Pt/H0UV+cU+eWHRV43qs9Aki77yI559ftWtNV4HKRFCjfpgZ5GaT9H7RxeyVMrVLDjsoGADwMEaSd4EdVyiCKe7bHkFcLIGvOZ+hEprMrGKDovztop8Sd9iLUJpBuo+DdHvvpxB2ZnpDuRzv4ONO0hZso4UfNw+9krz3QHS3GPDqRJkBwR8GW6gtE7hme+keKOAyuVWUuHxw+bKIOvY+2zMXK2yTCOwT9RUY32wh2rqYuI5ZjmHDriKvQMsV3qPZQUQ5nJEjoLCHmokLJS1BdcjY=
  - secure: eFFqlRoBCwG20mmCdFxrm9c54UMctr32ZftwIz3crq9MLzdUxvXslKxlHoD9g5EJs1rtZVFJxCvcjXvmq9b1d2NaEeG9b2/HzodgshK7T1Xg4Wy+8L16qfXi2BVEZvvjf5asH1wRKk4bRelDkLk1RkMKbun7nBTmxzfHxNHhPfDNTl0lg+3/uPAL4NnYKQpPQTHz2eYjHL+1SJeeStgrqHc51ozpsoDxNo1dlu7RsDe6cuHtJGHU09m8sraPjJV56zSUBY1mMxfsSDeTxRbB/IAF5XngnObwPC4IEAOf42+T4B0tTed+RKGBoUXs82bn+vuwWv+2EhC0YGPn+IHujrx2lJsq4FdYnJKVjp84p83ZrDMBdvBlnr4X2s2ex9s5eJ4eNeLdivdKk0b3gQhID14niXu9AQxkzwKFLmv10EeamYYazHYgHU98huZHcxlfYBgt/ZcCI/59TW3WVZZS+jzdRqzYX5+Yjhj2GEZpyK06zDM97uJ4wiNgz5aB8OHEis4/A3sTcofymIapCvjWLqlWVPNPH7L3S1m4oLmCwD+qFz9M7Ggt4+PYgDBVnmKZVsqn0xz4wp1kRm47y15jmqVTmRZ5fuRdHEtWujN91hKacVELaWOD886j70SrmAHWcjEENgVbcgDomgYB+Cy9Vt0nHlDJwWFUd7zQt28ANAQ=
