export default [
  { key: 'babyBath', title: 'Baby bath' },
  { key: 'babyMonitor', title: 'Baby monitor' },
  { key: 'sabysitter', title: 'Babysitter recommendations' },
  { key: 'bathtub', title: 'Bathtub' },
  { key: 'changingTable', title: 'Changing table' },
  { key: 'childrenToys', title: 'Children’s books and toys' },
  { key: 'childrenDinnerware', title: 'Children’s dinnerware' },
  { key: 'crib', title: 'Crib' },
  { key: 'fireplaceGuards', title: 'Fireplace guards' },
  { key: 'gameConsole', title: 'Game console' },
  { key: 'highChair', title: 'High chair' },
  { key: 'outletCovers', title: 'Outlet covers' },
  { key: 'packNPlay', title: 'Pack ’n Play/travel crib' },
  { key: 'roomDarkenong', title: 'Room-darkening shades' },
  { key: 'stairGates', title: 'Stair gates' },
  { key: 'tableCornerGuards', title: 'Table corner guards' },
  { key: 'windowGuards', title: 'Window guards' },
];
